#!/usr/bin/env node
/**
 * Auto-generate X2000 manifest from codebase
 *
 * Run: npx ts-node scripts/generate-manifest.ts
 *      OR node --loader ts-node/esm scripts/generate-manifest.ts
 *
 * This script scans the codebase and generates:
 * 1. src/manifest.ts - TypeScript manifest with types
 * 2. Updates CLAUDE.md stats section
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'src');

interface ManifestData {
  version: string;
  generatedAt: string;
  brains: { count: number; list: string[] };
  llmProviders: { count: number; list: string[] };
  channels: { count: number; list: string[] };
  tools: { count: number; list: string[] };
  sandbox: { levels: string[] };
  stats: { sourceFiles: number; linesOfCode: number; designDocs: number };
}

function scanDirectory(dir: string, pattern?: RegExp): string[] {
  if (!fs.existsSync(dir)) return [];

  return fs.readdirSync(dir, { withFileTypes: true })
    .filter(d => {
      if (pattern) return pattern.test(d.name);
      return d.isDirectory() && !d.name.startsWith('.');
    })
    .map(d => d.name.replace(/\.ts$/, ''));
}

function countFiles(dir: string, ext: string): number {
  let count = 0;

  function walk(d: string) {
    if (!fs.existsSync(d)) return;
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      const fullPath = path.join(d, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (entry.name.endsWith(ext)) {
        count++;
      }
    }
  }

  walk(dir);
  return count;
}

function countLines(dir: string, ext: string): number {
  let lines = 0;

  function walk(d: string) {
    if (!fs.existsSync(d)) return;
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      const fullPath = path.join(d, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (entry.name.endsWith(ext)) {
        const content = fs.readFileSync(fullPath, 'utf-8');
        lines += content.split('\n').length;
      }
    }
  }

  walk(dir);
  return lines;
}

function generateManifest(): ManifestData {
  // Scan brains from X2000 only (merged - single source of truth)
  const brainsDir = path.join(SRC, 'brains');
  const brains = scanDirectory(brainsDir)
    .filter(b => b !== 'base' && b !== 'index');

  // Scan LLM providers
  const llmProvidersDir = path.join(SRC, 'llm', 'providers');
  const llmProviders = scanDirectory(llmProvidersDir, /\.ts$/)
    .filter(p => p !== 'index');

  // Scan channels
  const channelsAdaptersDir = path.join(SRC, 'channels', 'adapters');
  const channels = scanDirectory(channelsAdaptersDir, /\.ts$/)
    .filter(c => c !== 'index')
    .map(c => c.replace('-channel', ''));

  // Add base channels
  const baseChannels = ['api', 'discord', 'slack'];
  const allChannels = [...new Set([...baseChannels, ...channels])];

  // Scan tools
  const toolsDir = path.join(SRC, 'tools');
  const tools = scanDirectory(toolsDir, /\.ts$/)
    .filter(t => !['base', 'index', 'test-tools'].includes(t));

  // Scan sandbox levels
  const sandboxLevelsDir = path.join(SRC, 'sandbox', 'levels');
  const sandboxLevels = scanDirectory(sandboxLevelsDir, /\.ts$/);

  // Count stats
  const sourceFiles = countFiles(SRC, '.ts');
  const linesOfCode = countLines(SRC, '.ts');
  const designDocs = countFiles(path.join(ROOT, 'docs', 'designs'), '.md');

  return {
    version: '0.1.0',
    generatedAt: new Date().toISOString(),
    brains: { count: brains.length, list: brains.sort() },
    llmProviders: { count: llmProviders.length, list: llmProviders.sort() },
    channels: { count: allChannels.length, list: allChannels.sort() },
    tools: { count: tools.length, list: tools.sort() },
    sandbox: { levels: sandboxLevels.sort() },
    stats: { sourceFiles, linesOfCode, designDocs },
  };
}

function writeManifestTS(data: ManifestData) {
  const content = `/**
 * X2000 Auto-Generated Manifest
 *
 * Generated by: scripts/generate-manifest.ts
 * DO NOT EDIT MANUALLY - run the script to regenerate
 *
 * Last updated: ${data.generatedAt}
 */

export const X2000_MANIFEST = {
  version: '${data.version}',
  generatedAt: '${data.generatedAt}',

  brains: {
    count: ${data.brains.count},
    list: [
${data.brains.list.map(b => `      '${b}',`).join('\n')}
    ],
  },

  llmProviders: {
    count: ${data.llmProviders.count},
    list: [
${data.llmProviders.list.map(p => `      '${p}',`).join('\n')}
    ],
  },

  channels: {
    count: ${data.channels.count},
    list: [
${data.channels.list.map(c => `      '${c}',`).join('\n')}
    ],
  },

  tools: {
    count: ${data.tools.count},
    list: [
${data.tools.list.map(t => `      '${t}',`).join('\n')}
    ],
  },

  sandbox: {
    levels: [${data.sandbox.levels.map(l => `'${l}'`).join(', ')}],
  },

  stats: {
    sourceFiles: ${data.stats.sourceFiles},
    linesOfCode: ${data.stats.linesOfCode},
    designDocs: ${data.stats.designDocs},
  },
} as const;

export type BrainType = typeof X2000_MANIFEST.brains.list[number];
export type LLMProviderType = typeof X2000_MANIFEST.llmProviders.list[number];
export type ChannelType = typeof X2000_MANIFEST.channels.list[number];
export type ToolType = typeof X2000_MANIFEST.tools.list[number];
export type SandboxLevel = typeof X2000_MANIFEST.sandbox.levels[number];
`;

  fs.writeFileSync(path.join(SRC, 'manifest.ts'), content);
  console.log('✅ Generated src/manifest.ts');
}

function writeManifestJSON(data: ManifestData) {
  fs.writeFileSync(
    path.join(ROOT, 'manifest.json'),
    JSON.stringify(data, null, 2)
  );
  console.log('✅ Generated manifest.json');
}

function updateClaudeMD(data: ManifestData) {
  const claudeMDPath = path.join(ROOT, 'CLAUDE.md');
  if (!fs.existsSync(claudeMDPath)) return;

  let content = fs.readFileSync(claudeMDPath, 'utf-8');

  // Update stats in CLAUDE.md
  // Look for patterns like "37 specialized brains" or "37+ domains"
  content = content.replace(
    /(\d+)\s*(specialized\s+)?brains?/gi,
    `${data.brains.count} specialized brains`
  );

  content = content.replace(
    /\+ \d+ more/gi,
    `+ ${data.brains.count - 3} more`
  );

  fs.writeFileSync(claudeMDPath, content);
  console.log('✅ Updated CLAUDE.md with current stats');
}

// Main
const manifest = generateManifest();
writeManifestTS(manifest);
writeManifestJSON(manifest);
updateClaudeMD(manifest);

console.log('');
console.log('📊 X2000 Manifest Summary:');
console.log(`   Brains:        ${manifest.brains.count}`);
console.log(`   LLM Providers: ${manifest.llmProviders.count}`);
console.log(`   Channels:      ${manifest.channels.count}`);
console.log(`   Tools:         ${manifest.tools.count}`);
console.log(`   Source Files:  ${manifest.stats.sourceFiles}`);
console.log(`   Lines of Code: ${manifest.stats.linesOfCode.toLocaleString()}`);
