import { VideoEngineConfig, VideoEngine, SubscriptionTier } from '@/types/video-engine';

// Complete configuration for all video generation engines
export const VIDEO_ENGINES: Record<VideoEngine, VideoEngineConfig> = {
  // FREE TIER - Budget Option
  'hailuo-02': {
    id: 'hailuo-02',
    name: 'hailuo-02',
    displayName: 'Hailuo 02',
    version: '2.0',
    provider: 'Minimax',
    pricePerSecond: 0.028,
    maxLength: 10,
    resolution: ['768p', '1080p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'free',
    badge: '#2 Globally',
    rank: 'Ranked #2 on Artificial Analysis',
    speed: 'ultra-fast',
    features: [
      '2.5x faster inference',
      '3x larger parameters',
      'Beats Google Veo 3',
      '1080p @ 10 seconds',
    ],
    apiProvider: 'fal-ai',
  },

  // STARTER TIER - Best Value
  'runway-gen4-turbo': {
    id: 'runway-gen4-turbo',
    name: 'runway-gen4-turbo',
    displayName: 'Runway Gen-4 Turbo',
    version: '4.0 Turbo',
    provider: 'Runway',
    pricePerSecond: 0.05,
    maxLength: 120,
    resolution: ['720p', '1080p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'starter',
    badge: '3x Faster',
    speed: 'fast',
    features: [
      'Cinematic quality',
      '30s to generate 10s video',
      'Character consistency',
      'Object tracking',
    ],
    apiProvider: 'direct',
  },

  'runway-gen4-aleph': {
    id: 'runway-gen4-aleph',
    name: 'runway-gen4-aleph',
    displayName: 'Runway Gen-4 Aleph',
    version: '4.0 Aleph',
    provider: 'Runway',
    pricePerSecond: 0.15,
    maxLength: 120,
    resolution: ['1080p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'pro',
    badge: 'Premium',
    speed: 'standard',
    features: [
      'Highest fidelity',
      'Advanced effects',
      'Professional grade',
      'Cinema-ready',
    ],
    apiProvider: 'direct',
  },

  // CREATOR TIER - #1 Ranked
  'kling-2.1': {
    id: 'kling-2.1',
    name: 'kling-2.1',
    displayName: 'Kling 2.1',
    version: '2.1',
    provider: 'Kuaishou',
    pricePerSecond: 0.10,
    maxLength: 10,
    resolution: ['720p', '1080p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'creator',
    badge: '#1 Ranked',
    rank: 'Tied #1 with Veo 3 (93.5/100)',
    speed: 'standard',
    features: [
      'Start/End frame conditioning',
      '61% user preference',
      'Motion realism',
      'Prompt adherence',
    ],
    apiProvider: 'fal-ai',
  },

  // AGENCY TIER - Most Advanced
  'veo-3.1': {
    id: 'veo-3.1',
    name: 'veo-3.1',
    displayName: 'Google Veo 3.1',
    version: '3.1',
    provider: 'Google DeepMind',
    pricePerSecond: 0.40,
    maxLength: 148,
    resolution: ['720p', '1080p'],
    hasNativeAudio: true,
    apiStatus: 'available',
    tier: 'agency',
    badge: 'Latest',
    rank: 'Tied #1 (93.5/100)',
    speed: 'standard',
    features: [
      'Scene extension (60+ seconds)',
      'Frame interpolation',
      'Up to 3 reference images',
      'Native audio generation',
      'Richer audio sync',
    ],
    apiProvider: 'direct',
  },

  'veo-3.1-fast': {
    id: 'veo-3.1-fast',
    name: 'veo-3.1-fast',
    displayName: 'Google Veo 3.1 Fast',
    version: '3.1 Fast',
    provider: 'Google DeepMind',
    pricePerSecond: 0.15,
    maxLength: 148,
    resolution: ['720p', '1080p'],
    hasNativeAudio: true,
    apiStatus: 'available',
    tier: 'pro',
    badge: 'Fast',
    speed: 'fast',
    features: [
      'Scene extension',
      'Native audio',
      'Faster generation',
      'Cost-effective',
    ],
    apiProvider: 'direct',
  },

  // ENTERPRISE TIER - Premium Quality
  'sora-2': {
    id: 'sora-2',
    name: 'sora-2',
    displayName: 'OpenAI Sora 2',
    version: '2.0',
    provider: 'OpenAI',
    pricePerSecond: 0.30,
    maxLength: 20,
    resolution: ['720p', '1080p'],
    hasNativeAudio: true,
    apiStatus: 'preview',
    tier: 'enterprise',
    badge: 'API Preview',
    speed: 'standard',
    features: [
      'Photorealistic quality',
      'Synchronized dialogue',
      'Azure integration',
      'Image-to-video',
    ],
    apiProvider: 'direct',
  },

  'sora-2-pro': {
    id: 'sora-2-pro',
    name: 'sora-2-pro',
    displayName: 'OpenAI Sora 2 Pro',
    version: '2.0 Pro',
    provider: 'OpenAI',
    pricePerSecond: 0.50,
    maxLength: 20,
    resolution: ['1080p'],
    hasNativeAudio: true,
    apiStatus: 'preview',
    tier: 'enterprise',
    badge: 'Premium',
    speed: 'standard',
    features: [
      'Best quality',
      'HD 1080p',
      'Advanced controls',
      'Priority access',
    ],
    apiProvider: 'direct',
  },

  // ADDITIONAL OPTIONS
  'wan-2.5': {
    id: 'wan-2.5',
    name: 'wan-2.5',
    displayName: 'Wan 2.5',
    version: '2.5',
    provider: 'Alibaba',
    pricePerSecond: 0.08,
    maxLength: 10,
    resolution: ['720p', '1080p'],
    hasNativeAudio: true,
    apiStatus: 'available',
    tier: 'creator',
    badge: 'Audio-Visual',
    speed: 'standard',
    features: [
      'Native audio-visual sync',
      'Multi-language support',
      'Lip-sync precision',
      'Social media optimized',
    ],
    apiProvider: 'fal-ai',
  },

  'pika-2.2': {
    id: 'pika-2.2',
    name: 'pika-2.2',
    displayName: 'Pika 2.2',
    version: '2.2',
    provider: 'Pika Labs',
    pricePerSecond: 0.156,
    maxLength: 10,
    resolution: ['720p', '1080p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'pro',
    badge: 'Keyframes',
    speed: 'standard',
    features: [
      'Pikaframes technology',
      'Keyframe transitions',
      '1-10 second smooth transitions',
      'Creative effects',
    ],
    apiProvider: 'direct',
  },

  'luma-ray3': {
    id: 'luma-ray3',
    name: 'luma-ray3',
    displayName: 'Luma Ray 3',
    version: '3.0',
    provider: 'Luma AI',
    pricePerSecond: 0.066,
    maxLength: 10,
    resolution: ['540p', '720p', '1080p HDR'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'pro',
    badge: 'Reasoning',
    rank: "World's First Reasoning Model",
    speed: 'standard',
    features: [
      '16-bit HDR output',
      'Visual reasoning',
      'Physics simulation',
      'Professional color grading',
    ],
    apiProvider: 'fal-ai',
  },

  'nova-reel': {
    id: 'nova-reel',
    name: 'nova-reel',
    displayName: 'Amazon Nova Reel',
    version: '1.1',
    provider: 'AWS',
    pricePerSecond: 0.08,
    maxLength: 120,
    resolution: ['720p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'agency',
    badge: 'Enterprise',
    speed: 'standard',
    features: [
      'Up to 2 minutes',
      'Multi-shot videos',
      'AWS infrastructure',
      'Enterprise security',
    ],
    apiProvider: 'direct',
  },

  // NEW: Runway Gen-3 Alpha
  'runway-gen3-alpha': {
    id: 'runway-gen3-alpha',
    name: 'runway-gen3-alpha',
    displayName: 'Runway Gen-3 Alpha',
    version: '3.0 Alpha',
    provider: 'Runway',
    pricePerSecond: 0.08,
    maxLength: 120,
    resolution: ['720p', '1080p'],
    hasNativeAudio: true,
    apiStatus: 'available',
    tier: 'pro',
    badge: 'Latest',
    speed: 'fast',
    features: [
      'Gen-3 with audio',
      'Faster than Gen-4',
      'Audio-visual sync',
      'Professional quality',
    ],
    apiProvider: 'fal-ai',
  },

  // NEW: Kling 2.5 Turbo
  'kling-2.5-turbo': {
    id: 'kling-2.5-turbo',
    name: 'kling-2.5-turbo',
    displayName: 'Kling 2.5 Turbo',
    version: '2.5 Turbo',
    provider: 'Kuaishou',
    pricePerSecond: 0.15,
    maxLength: 10,
    resolution: ['720p', '1080p'],
    hasNativeAudio: true,
    apiStatus: 'available',
    tier: 'pro',
    badge: 'Upgraded',
    speed: 'fast',
    features: [
      'Faster than 2.1',
      'Audio generation',
      'Better motion',
      'Enhanced quality',
    ],
    apiProvider: 'fal-ai',
  },

  // NEW: Kling 2.5 Turbo Pro
  'kling-2.5-turbo-pro': {
    id: 'kling-2.5-turbo-pro',
    name: 'kling-2.5-turbo-pro',
    displayName: 'Kling 2.5 Turbo Pro',
    version: '2.5 Turbo Pro',
    provider: 'Kuaishou',
    pricePerSecond: 0.22,
    maxLength: 10,
    resolution: ['1080p'],
    hasNativeAudio: true,
    apiStatus: 'available',
    tier: 'agency',
    badge: 'Premium',
    speed: 'standard',
    features: [
      'Highest Kling quality',
      'Cinematic fidelity',
      'Professional audio',
      'Best motion physics',
    ],
    apiProvider: 'fal-ai',
  },

  // NEW: Hunyuan Video (Chinese Killer!)
  'hunyuan-video': {
    id: 'hunyuan-video',
    name: 'hunyuan-video',
    displayName: 'Hunyuan Video',
    version: '1.0',
    provider: 'Tencent',
    pricePerSecond: 0.06,
    maxLength: 16,
    resolution: ['720p', '1080p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'starter',
    badge: 'Beats Gen-3',
    rank: 'Beats Runway Gen-3 in benchmarks',
    speed: 'fast',
    features: [
      '13B parameters',
      'Studio-grade quality',
      '16-second clips',
      'Open source',
      'Best value ($0.06/sec)',
    ],
    apiProvider: 'fal-ai',
  },

  // NEW: Vidu Q2
  'vidu-q2': {
    id: 'vidu-q2',
    name: 'vidu-q2',
    displayName: 'Vidu Q2',
    version: 'Q2',
    provider: 'ShengShu',
    pricePerSecond: 0.05,
    maxLength: 10,
    resolution: ['720p', '1080p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'starter',
    badge: 'Ultra-Fast',
    speed: 'ultra-fast',
    features: [
      '10-second generation',
      '7 reference images',
      'Multiple-entity consistency',
      'Reference-to-video',
    ],
    apiProvider: 'fal-ai',
  },

  // NEW: Seedance 1.0 Pro (Budget King!)
  'seedance-1.0-pro': {
    id: 'seedance-1.0-pro',
    name: 'seedance-1.0-pro',
    displayName: 'Seedance 1.0 Pro',
    version: '1.0 Pro',
    provider: 'Seedance',
    pricePerSecond: 0.04,
    maxLength: 10,
    resolution: ['720p', '1080p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'free',
    badge: 'Budget',
    speed: 'ultra-fast',
    features: [
      'Cheapest option',
      'Maximum performance',
      'Minimal cost',
      'Fast generation',
    ],
    apiProvider: 'fal-ai',
  },

  // NEW: PixVerse v4.5
  'pixverse-v4.5': {
    id: 'pixverse-v4.5',
    name: 'pixverse-v4.5',
    displayName: 'PixVerse v4.5',
    version: '4.5',
    provider: 'PixVerse',
    pricePerSecond: 0.07,
    maxLength: 10,
    resolution: ['720p', '1080p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'starter',
    badge: 'Fast',
    speed: 'fast',
    features: [
      'Text and image prompts',
      'High quality',
      'Fast generation',
      'Social media optimized',
    ],
    apiProvider: 'fal-ai',
  },

  // NEW: LTX-2 Pro (with Audio!)
  'ltx-2-pro': {
    id: 'ltx-2-pro',
    name: 'ltx-2-pro',
    displayName: 'LTX-2 Pro',
    version: '2.0 Pro',
    provider: 'Lightricks',
    pricePerSecond: 0.10,
    maxLength: 10,
    resolution: ['720p', '1080p'],
    hasNativeAudio: true,
    apiStatus: 'available',
    tier: 'creator',
    badge: 'Audio',
    speed: 'fast',
    features: [
      'High-fidelity video',
      'Native audio',
      'Professional quality',
      'Fast generation',
    ],
    apiProvider: 'fal-ai',
  },

  // NEW: WAN 2.2
  'wan-2.2': {
    id: 'wan-2.2',
    name: 'wan-2.2',
    displayName: 'WAN 2.2',
    version: '2.2',
    provider: 'Krea',
    pricePerSecond: 0.09,
    maxLength: 10,
    resolution: ['720p', '1080p'],
    hasNativeAudio: true,
    apiStatus: 'available',
    tier: 'creator',
    badge: 'Cinematic',
    speed: 'standard',
    features: [
      'Cinematic quality',
      'Audio generation',
      'Professional effects',
      'Style control',
    ],
    apiProvider: 'fal-ai',
  },

  // NEW: Mochi 1
  'mochi-1': {
    id: 'mochi-1',
    name: 'mochi-1',
    displayName: 'Mochi 1',
    version: '1.0',
    provider: 'Genmo',
    pricePerSecond: 0.06,
    maxLength: 10,
    resolution: ['720p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'starter',
    badge: 'Open Source',
    speed: 'standard',
    features: [
      'Open source model',
      'Good quality',
      'Budget-friendly',
      'Community-driven',
    ],
    apiProvider: 'fal-ai',
  },

  // NEW: Fabric 1.0
  'fabric-1.0': {
    id: 'fabric-1.0',
    name: 'fabric-1.0',
    displayName: 'Fabric 1.0',
    version: '1.0',
    provider: 'VEED',
    pricePerSecond: 0.07,
    maxLength: 20,
    resolution: ['720p', '1080p'],
    hasNativeAudio: true,
    apiStatus: 'available',
    tier: 'creator',
    badge: 'Long-form',
    speed: 'fast',
    features: [
      'Up to 20 seconds',
      'Faster generation',
      'Audio support',
      'Longer outputs',
    ],
    apiProvider: 'fal-ai',
  },

  // NEW: CogVideoX 5B (Open Source!)
  'cogvideox-5b': {
    id: 'cogvideox-5b',
    name: 'cogvideox-5b',
    displayName: 'CogVideoX 5B',
    version: '5B',
    provider: 'Tsinghua University',
    pricePerSecond: 0.02,
    maxLength: 6,
    resolution: ['720x480'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'free',
    badge: 'Open Source',
    speed: 'standard',
    features: [
      'Fully open source',
      'Self-hostable',
      'Cheapest option',
      '8-12GB GPU',
      'Community support',
    ],
    apiProvider: 'replicate',
  },

  // NEW: CogVideoX I2V (Image-to-Video)
  'cogvideox-i2v': {
    id: 'cogvideox-i2v',
    name: 'cogvideox-i2v',
    displayName: 'CogVideoX I2V',
    version: 'I2V',
    provider: 'Tsinghua University',
    pricePerSecond: 0.025,
    maxLength: 6,
    resolution: ['Any'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'free',
    badge: 'Image-to-Video',
    speed: 'standard',
    features: [
      'Image-to-video',
      'Any resolution',
      'Open source',
      'Self-hostable',
      'Community-driven',
    ],
    apiProvider: 'replicate',
  },
};

// Optimized 4-Tier Subscription System
// Strategy: Drive users to Pro (ALL engines), differentiate by tokens & social accounts
export const SUBSCRIPTION_TIERS: SubscriptionTier[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    videoCredits: 300, // tokens, not video count
    engines: [
      'hailuo-02',
      'hunyuan-video',
      'cogvideox-5b',
      'cogvideox-i2v',
      'seedance-1.0-pro',
    ],
    features: [
      '300 tokens/month (~3-6 videos)',
      '1 social media account',
      '5 budget engines',
      'Up to 10s videos',
      '1080p resolution',
      'Watermark included',
      'Community support',
    ],
  },
  {
    id: 'starter',
    name: 'Starter',
    price: 29,
    videoCredits: 2000, // tokens
    engines: [
      'hailuo-02',
      'hunyuan-video',
      'cogvideox-5b',
      'cogvideox-i2v',
      'seedance-1.0-pro',
      'runway-gen4-turbo',
      'kling-2.1',
      'pixverse-v4.5',
      'wan-2.2',
      'vidu-q2',
      'mochi-1',
      'fabric-1.0',
    ],
    features: [
      '2,000 tokens/month (~20-40 videos)',
      '2 social media accounts',
      '12 professional engines',
      'Up to 30s videos',
      'No watermark',
      'Multi-platform posting',
      'Priority email support',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 99,
    videoCredits: 6000, // tokens
    popular: true,
    engines: [
      // ALL 25 ENGINES
      'hailuo-02',
      'runway-gen4-turbo',
      'runway-gen4-aleph',
      'runway-gen3-alpha',
      'kling-2.1',
      'kling-2.5-turbo',
      'kling-2.5-turbo-pro',
      'veo-3.1',
      'veo-3.1-fast',
      'sora-2',
      'sora-2-pro',
      'hunyuan-video',
      'vidu-q2',
      'seedance-1.0-pro',
      'pixverse-v4.5',
      'ltx-2-pro',
      'wan-2.2',
      'wan-2.5',
      'pika-2.2',
      'luma-ray3',
      'nova-reel',
      'mochi-1',
      'fabric-1.0',
      'cogvideox-5b',
      'cogvideox-i2v',
    ],
    features: [
      '6,000 tokens/month (~60-120 videos)',
      '5 social media accounts',
      '🔥 ALL 25 VIDEO ENGINES',
      'OpenAI Sora 2 & Sora 2 Pro',
      'Google Veo 3.1 full access',
      'Up to 148s videos',
      '1080p HDR output',
      'Native audio on 15+ engines',
      'Unlimited content library',
      'API access (basic)',
      'Advanced analytics',
      'Campaign management',
      'Commercial license',
      'Priority support',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 299,
    videoCredits: 20000, // tokens
    engines: [
      // ALL 25 ENGINES (same as Pro)
      'hailuo-02',
      'runway-gen4-turbo',
      'runway-gen4-aleph',
      'runway-gen3-alpha',
      'kling-2.1',
      'kling-2.5-turbo',
      'kling-2.5-turbo-pro',
      'veo-3.1',
      'veo-3.1-fast',
      'sora-2',
      'sora-2-pro',
      'hunyuan-video',
      'vidu-q2',
      'seedance-1.0-pro',
      'pixverse-v4.5',
      'ltx-2-pro',
      'wan-2.2',
      'wan-2.5',
      'pika-2.2',
      'luma-ray3',
      'nova-reel',
      'mochi-1',
      'fabric-1.0',
      'cogvideox-5b',
      'cogvideox-i2v',
    ],
    features: [
      '20,000 tokens/month (custom available)',
      'Unlimited social media accounts',
      'Unlimited team members',
      'ALL 25 video engines',
      'White-label branding',
      'Dedicated account manager',
      'Custom integrations',
      'API access (advanced + priority)',
      'SLA guarantees (99.9%)',
      'Custom model training',
      'Azure/AWS integration',
      'SSO & enterprise security',
      'Quarterly business reviews',
    ],
  },
];

// Auto-select best engine per tier when user chooses "auto"
export const ENGINE_BY_TIER: Record<string, VideoEngine> = {
  free: 'hunyuan-video',      // Best value engine (beats Gen-3)
  starter: 'kling-2.1',        // #1 ranked engine
  pro: 'veo-3.1',              // Full Google Veo 3.1
  enterprise: 'sora-2-pro',    // Premium OpenAI Sora
};

// Helper function to get available engines for a tier
export function getEnginesForTier(tier: string): VideoEngineConfig[] {
  const subscriptionTier = SUBSCRIPTION_TIERS.find((t) => t.id === tier);
  if (!subscriptionTier) return [];

  return subscriptionTier.engines.map((engineId) => VIDEO_ENGINES[engineId]);
}

// Helper function to check if user has access to engine
export function hasEngineAccess(userTier: string, engine: VideoEngine): boolean {
  const subscriptionTier = SUBSCRIPTION_TIERS.find((t) => t.id === userTier);
  if (!subscriptionTier) return false;

  return subscriptionTier.engines.includes(engine);
}
