import { VideoEngineConfig, VideoEngine, SubscriptionTier } from '@/types/video-engine';

// Complete configuration for all video generation engines
export const VIDEO_ENGINES: Record<VideoEngine, VideoEngineConfig> = {
  // FREE TIER - Budget Option
  'hailuo-02': {
    id: 'hailuo-02',
    name: 'hailuo-02',
    displayName: 'Hailuo 02',
    version: '2.0',
    provider: 'Minimax',
    pricePerSecond: 0.028,
    maxLength: 10,
    resolution: ['768p', '1080p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'free',
    badge: '#2 Globally',
    rank: 'Ranked #2 on Artificial Analysis',
    speed: 'ultra-fast',
    features: [
      '2.5x faster inference',
      '3x larger parameters',
      'Beats Google Veo 3',
      '1080p @ 10 seconds',
    ],
    apiProvider: 'fal-ai',
  },

  // STARTER TIER - Best Value
  'runway-gen4-turbo': {
    id: 'runway-gen4-turbo',
    name: 'runway-gen4-turbo',
    displayName: 'Runway Gen-4 Turbo',
    version: '4.0 Turbo',
    provider: 'Runway',
    pricePerSecond: 0.05,
    maxLength: 120,
    resolution: ['720p', '1080p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'starter',
    badge: '3x Faster',
    speed: 'fast',
    features: [
      'Cinematic quality',
      '30s to generate 10s video',
      'Character consistency',
      'Object tracking',
    ],
    apiProvider: 'direct',
  },

  'runway-gen4-aleph': {
    id: 'runway-gen4-aleph',
    name: 'runway-gen4-aleph',
    displayName: 'Runway Gen-4 Aleph',
    version: '4.0 Aleph',
    provider: 'Runway',
    pricePerSecond: 0.15,
    maxLength: 120,
    resolution: ['1080p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'pro',
    badge: 'Premium',
    speed: 'standard',
    features: [
      'Highest fidelity',
      'Advanced effects',
      'Professional grade',
      'Cinema-ready',
    ],
    apiProvider: 'direct',
  },

  // CREATOR TIER - #1 Ranked
  'kling-2.1': {
    id: 'kling-2.1',
    name: 'kling-2.1',
    displayName: 'Kling 2.1',
    version: '2.1',
    provider: 'Kuaishou',
    pricePerSecond: 0.10,
    maxLength: 10,
    resolution: ['720p', '1080p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'creator',
    badge: '#1 Ranked',
    rank: 'Tied #1 with Veo 3 (93.5/100)',
    speed: 'standard',
    features: [
      'Start/End frame conditioning',
      '61% user preference',
      'Motion realism',
      'Prompt adherence',
    ],
    apiProvider: 'fal-ai',
  },

  // AGENCY TIER - Most Advanced
  'veo-3.1': {
    id: 'veo-3.1',
    name: 'veo-3.1',
    displayName: 'Google Veo 3.1',
    version: '3.1',
    provider: 'Google DeepMind',
    pricePerSecond: 0.40,
    maxLength: 148,
    resolution: ['720p', '1080p'],
    hasNativeAudio: true,
    apiStatus: 'available',
    tier: 'agency',
    badge: 'Latest',
    rank: 'Tied #1 (93.5/100)',
    speed: 'standard',
    features: [
      'Scene extension (60+ seconds)',
      'Frame interpolation',
      'Up to 3 reference images',
      'Native audio generation',
      'Richer audio sync',
    ],
    apiProvider: 'direct',
  },

  'veo-3.1-fast': {
    id: 'veo-3.1-fast',
    name: 'veo-3.1-fast',
    displayName: 'Google Veo 3.1 Fast',
    version: '3.1 Fast',
    provider: 'Google DeepMind',
    pricePerSecond: 0.15,
    maxLength: 148,
    resolution: ['720p', '1080p'],
    hasNativeAudio: true,
    apiStatus: 'available',
    tier: 'pro',
    badge: 'Fast',
    speed: 'fast',
    features: [
      'Scene extension',
      'Native audio',
      'Faster generation',
      'Cost-effective',
    ],
    apiProvider: 'direct',
  },

  // ENTERPRISE TIER - Premium Quality
  'sora-2': {
    id: 'sora-2',
    name: 'sora-2',
    displayName: 'OpenAI Sora 2',
    version: '2.0',
    provider: 'OpenAI',
    pricePerSecond: 0.30,
    maxLength: 20,
    resolution: ['720p', '1080p'],
    hasNativeAudio: true,
    apiStatus: 'preview',
    tier: 'enterprise',
    badge: 'API Preview',
    speed: 'standard',
    features: [
      'Photorealistic quality',
      'Synchronized dialogue',
      'Azure integration',
      'Image-to-video',
    ],
    apiProvider: 'direct',
  },

  'sora-2-pro': {
    id: 'sora-2-pro',
    name: 'sora-2-pro',
    displayName: 'OpenAI Sora 2 Pro',
    version: '2.0 Pro',
    provider: 'OpenAI',
    pricePerSecond: 0.50,
    maxLength: 20,
    resolution: ['1080p'],
    hasNativeAudio: true,
    apiStatus: 'preview',
    tier: 'enterprise',
    badge: 'Premium',
    speed: 'standard',
    features: [
      'Best quality',
      'HD 1080p',
      'Advanced controls',
      'Priority access',
    ],
    apiProvider: 'direct',
  },

  // ADDITIONAL OPTIONS
  'wan-2.5': {
    id: 'wan-2.5',
    name: 'wan-2.5',
    displayName: 'Wan 2.5',
    version: '2.5',
    provider: 'Alibaba',
    pricePerSecond: 0.08,
    maxLength: 10,
    resolution: ['720p', '1080p'],
    hasNativeAudio: true,
    apiStatus: 'available',
    tier: 'creator',
    badge: 'Audio-Visual',
    speed: 'standard',
    features: [
      'Native audio-visual sync',
      'Multi-language support',
      'Lip-sync precision',
      'Social media optimized',
    ],
    apiProvider: 'fal-ai',
  },

  'pika-2.2': {
    id: 'pika-2.2',
    name: 'pika-2.2',
    displayName: 'Pika 2.2',
    version: '2.2',
    provider: 'Pika Labs',
    pricePerSecond: 0.156,
    maxLength: 10,
    resolution: ['720p', '1080p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'pro',
    badge: 'Keyframes',
    speed: 'standard',
    features: [
      'Pikaframes technology',
      'Keyframe transitions',
      '1-10 second smooth transitions',
      'Creative effects',
    ],
    apiProvider: 'direct',
  },

  'luma-ray3': {
    id: 'luma-ray3',
    name: 'luma-ray3',
    displayName: 'Luma Ray 3',
    version: '3.0',
    provider: 'Luma AI',
    pricePerSecond: 0.066,
    maxLength: 10,
    resolution: ['540p', '720p', '1080p HDR'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'pro',
    badge: 'Reasoning',
    rank: "World's First Reasoning Model",
    speed: 'standard',
    features: [
      '16-bit HDR output',
      'Visual reasoning',
      'Physics simulation',
      'Professional color grading',
    ],
    apiProvider: 'fal-ai',
  },

  'nova-reel': {
    id: 'nova-reel',
    name: 'nova-reel',
    displayName: 'Amazon Nova Reel',
    version: '1.1',
    provider: 'AWS',
    pricePerSecond: 0.08,
    maxLength: 120,
    resolution: ['720p'],
    hasNativeAudio: false,
    apiStatus: 'available',
    tier: 'agency',
    badge: 'Enterprise',
    speed: 'standard',
    features: [
      'Up to 2 minutes',
      'Multi-shot videos',
      'AWS infrastructure',
      'Enterprise security',
    ],
    apiProvider: 'direct',
  },
};

// Subscription tiers with updated pricing
export const SUBSCRIPTION_TIERS: SubscriptionTier[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    videoCredits: 3,
    engines: ['hailuo-02'],
    features: [
      '3 AI videos per month',
      'Hailuo 02 engine (#2 globally)',
      'Up to 10 seconds',
      '1080p resolution',
      'Watermark included',
    ],
  },
  {
    id: 'starter',
    name: 'Starter',
    price: 29,
    videoCredits: 15,
    engines: ['hailuo-02', 'runway-gen4-turbo'],
    features: [
      '15 AI videos per month',
      'Runway Gen-4 Turbo',
      'Cinematic quality',
      'No watermark',
      'Priority support',
    ],
  },
  {
    id: 'creator',
    name: 'Creator',
    price: 79,
    videoCredits: 20,
    engines: ['hailuo-02', 'runway-gen4-turbo', 'kling-2.1', 'wan-2.5'],
    popular: true,
    features: [
      '20 AI videos per month',
      'Kling 2.1 (#1 ranked)',
      'Wan 2.5 with native audio',
      'Start/end frame control',
      'Commercial license',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 129,
    videoCredits: 25,
    engines: [
      'hailuo-02',
      'runway-gen4-turbo',
      'runway-gen4-aleph',
      'kling-2.1',
      'wan-2.5',
      'veo-3.1-fast',
      'luma-ray3',
      'pika-2.2',
    ],
    features: [
      '25 AI videos per month',
      'Google Veo 3.1 Fast',
      'Luma Ray 3 (reasoning)',
      'Scene extension',
      'HDR support',
      'Premium support',
    ],
  },
  {
    id: 'agency',
    name: 'Agency',
    price: 199,
    videoCredits: 40,
    engines: [
      'hailuo-02',
      'runway-gen4-turbo',
      'runway-gen4-aleph',
      'kling-2.1',
      'wan-2.5',
      'veo-3.1',
      'veo-3.1-fast',
      'luma-ray3',
      'pika-2.2',
      'nova-reel',
    ],
    features: [
      '40 AI videos per month',
      'Google Veo 3.1 (full)',
      'Amazon Nova Reel',
      'Up to 2-minute videos',
      'Frame interpolation',
      'White-label option',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 399,
    videoCredits: 40,
    engines: [
      'hailuo-02',
      'runway-gen4-turbo',
      'runway-gen4-aleph',
      'kling-2.1',
      'wan-2.5',
      'veo-3.1',
      'veo-3.1-fast',
      'sora-2',
      'sora-2-pro',
      'luma-ray3',
      'pika-2.2',
      'nova-reel',
    ],
    features: [
      '40+ premium AI videos',
      'OpenAI Sora 2 access',
      'All engines included',
      'Azure integration',
      'Dedicated account manager',
      'Custom integrations',
      'API access',
    ],
  },
];

// Engine selection by tier
export const ENGINE_BY_TIER: Record<string, VideoEngine> = {
  free: 'hailuo-02',
  starter: 'runway-gen4-turbo',
  creator: 'kling-2.1',
  pro: 'veo-3.1-fast',
  agency: 'veo-3.1',
  enterprise: 'sora-2',
};

// Helper function to get available engines for a tier
export function getEnginesForTier(tier: string): VideoEngineConfig[] {
  const subscriptionTier = SUBSCRIPTION_TIERS.find((t) => t.id === tier);
  if (!subscriptionTier) return [];

  return subscriptionTier.engines.map((engineId) => VIDEO_ENGINES[engineId]);
}

// Helper function to check if user has access to engine
export function hasEngineAccess(userTier: string, engine: VideoEngine): boolean {
  const subscriptionTier = SUBSCRIPTION_TIERS.find((t) => t.id === userTier);
  if (!subscriptionTier) return false;

  return subscriptionTier.engines.includes(engine);
}
